### ISSUE TITLE
启用插件报错

### ISSUE THREAD

**Issue by dazkarieh** [musnow/reward-for-typecho#2]
显示“Database Query Error”，怎么处理呀，提示信息

SQLSTATE[HY000]: General error: 1294 Invalid ON UPDATE clause for 'notify_time' column
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1294 Invalid ON UPDATE clause for 'notify_time' column in /www/wwwroot/xxx.com/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /www/wwwroot/xxx.com/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('CREATE TABLE `t...', Object(PDO), 2, 'SELECT')
#1 /www/wwwroot/xxx.com/usr/plugins/Reward/Plugin.php(36): Typecho_Db->query('CREATE TABLE `t...', 2)
#2 /www/wwwroot/xxx.com/var/Widget/Plugins/Edit.php(102): Reward_Plugin::activate()
#3 /www/wwwroot/xxx.com/var/Widget/Plugins/Edit.php(308): Widget_Plugins_Edit->activate('Reward')
#4 /www/wwwroot/xxx.com/var/Widget/Do.php(82): Widget_Plugins_Edit->action()
#5 /www/wwwroot/xxx.com/var/Typecho/Widget.php(221): Widget_Do->execute()
#6 /www/wwwroot/xxx.com/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#7 /www/wwwroot/xxx.com/index.php(23): Typecho_Router::dispatch()
#8 {main}

**Comment by musnow** [comment]
mysql版本可能有点低，你可以手动改一下字段类型

**Comment by dazkarieh** [comment]
不太懂SQL，希望楼上的大大可以兼容一下版本。

**Comment by fengtalk** [comment]
![image](https://user-images.githubusercontent.com/2913058/42291442-35d09c54-7ffe-11e8-9980-23cda38e89ed.png)
文章下方直接显示源代码

**Comment by musnow** [comment]
@fengtalk 更换过编辑器吗，如果不是的话可能需要升级typecho版本，我只在1.1上面测试过

**Comment by fengtalk** [comment]
@musnow 版本 1.1 (17.10.30)，系统自带的编辑器，禁用了其它插件也这样。

**Comment by cppfuns** [comment]
Database Query Error   +1

**Comment by fengtalk** [comment]
在一个全新安装的Typecho上，依然如故。 @musnow 
![image](https://user-images.githubusercontent.com/2913058/42365429-0d9156fa-8131-11e8-9fd8-0e4960247d95.png)
关闭“使用 Markdown 语法编辑和解析内容”可正常使用。

**Comment by daihao18** [comment]
升级到mysql 5.6即可
